import 'package:get/get.dart';

class LocalizeApp extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    "ar":{
      "appName": "InPacket",
      "borderTxt1": "اهلا وسهلا بكم في تطبيق InPaket",
      "borderTxt2": "جميع ما تطلبه بين يديك",
      "skip": "تخطي",
      "start": "إبدأ",
      "signIn": "تسجيل الدخول",
      "signUp": " أنشئ حساب",
      "forgetPassword":"نسيت كلمة المرور؟",
      "noAccount":"لا تمتلك حساب؟",
      "havAccount":"إذا كنت تمتلك حساب؟",

      "enterMobile":"ادخل رقم الهاتف",
      "password": "كلمة المرور",
      "newAccount": "تسجيل \nحساب جديد",
      "fullName":"الاسم كاملا",
      "phoneNumber":"رقم الهاتف",
      "city":"المدينة",
      "gender": "الجنس",
      "male": "ذكر",
      "female": "انثي",
      "confirmPassword": "تأكيد كلمة المرور",
      "resetPassword": "إستعادة كلمة المرور",
      "codeVerification": "رمز التحقق",
      "reset": "إعادة تعيين",
      "sentCode": "تم إرسال رمز التحقق الي رقم هاتفك",
      "verification" : "تحقق",
      "search": "شاشة البحث",
      "favorite": "المفضلة",
      "profile": "الصفحة الشخصية",
      "settingPanel": "لوحة التحكم",
      "location": "الموقع",
      "payment": "وسائل الدفع",
      "updateProfile":"تحديث البيانات الشخصية",
      "changePassword": "تحديث كلمة المرور",
      "notification":"الإشعارات",
      "activeNotification": "الاشعارات مفعلة",
      "disActiveNotification": "الإشعارات مغلقة",
      "signOut": "تسجيل الخروج",
      "language": "اللغة",
      "unKnown":"لم يحدد بعد",
      "country":"الدولة",
      "locality":"المدينة",
      "postalCode":"الرمز البريدي",
      "update":"تحديث",
      "orders": "الطلبات",
      "arabic":"اللغة العربية",
      "english":"اللغة الانجليزية",
      "turkish":"اللغة التركية",
      "kurdish":"اللغة الكردية",
      "quantity": "الكمية",
      "itemDescription": "تفاصيل المنتج",
      "price": "السعر",
      "rate": "التقييم",
      "books":"الكتب",
      "childGames":"ألعاب اطفال",
      "textiles":"منسوجات",
      "calcolation":"كالكوليشن",
      "cart":"السلة",
      "whatsapp":"واتس أب",
      "sections":"الأقسام",
      "services":"الخدمات" ,
      "contactUs":"تواصل معنا",
      "order": "إكمال الطلب",
      "cartTotal":"إجمالي الطلب",
      "tax":"التوصيل",
      "discount":"الخصم",
      "totalPrice":"إجمالي الرصيد",
      "favoriteCurrency":"إختر العملة المفضلة",
      "dollar"  :"دولار امريكي",
      "dinar"  : "دينار عراقي",
      "ok"  : "حسنا",
      "cancel"  : "إلغاء",
    },
    "en":{
      "appName": "InPacket",
      "borderTxt1": "Welcome to the InPaket App",
      "borderTxt2": "Your business is in your hands",
      "skip": "Skip",
      "start": "Start",
      "signIn": "Sign In",
      "signUp": "Sign Up",
      "forgetPassword":"Forget password?",
      "noAccount":"Don't have an account?",
      "havAccount":"Already have an account?",
      "enterMobile":"Enter Mobile Number",
      "password": "Password",
      "newAccount": "Register \nNew account",
      "fullName":"Full Name",
      "phoneNumber":"Phone Number",
      "city":"City",
      "gender": "Gender",
      "male": "Male",
      "female": "Female",
      "confirmPassword": "Confirm Password",
      "resetPassword": "ٌReset \nPassword",
      "reset": "Reset Password",
      "codeVerification": "Code\nVerification",
      "sentCode": "We have sent code verification to your mobile phone",
      "verification" : "Verification",
      "search": "Search",
      "favorite": "Favorite",
      "profile": "Profile",
      "settingPanel": "Setting Panel",
      "location": "Location",
      "payment": "Payment Method",
      "updateProfile":"Update Profile",
      "changePassword": "Update Password",
      "notification":"Notification",
      "activeNotification": "Notification is enabled",
      "disActiveNotification": "Notification is Closed",
      "signOut": "Sign Out",
      "language": "Language",
      "unKnown":"Not decided yet",
      "country":"Country",
      "locality":"City",
      "postalCode":"Postal Code",
      "update":"Update",
      "orders": "Orders",
      "arabic":"Arabic Language",
      "english":"English Language",
      "turkish":"Turkish language",
      "kurdish":"Kurdish language",
      "quantity": "Quantity",
      "itemDescription": "Product Description",
      "price": "Price",
      "rate": "Rate",
      "books":"Books",
      "childGames":"Child Game",
      "textiles":"Textiles",
      "calcolation":"Calcolation",
      "cart":"Cart",
      "whatsapp":"WhatAppً",
      "sections":"Sections",
      "services":"Services" ,
      "contactUs":"ContactUs",
      "order": "Complete Order",
      "cartTotal":"Cart Total",
      "tax":"Delivery",
      "discount":"Discount",
      "totalPrice":"Total Price",
      "favoriteCurrency":"Choose favorite currency",
      "dollar"  :"Dollar U.S",
      "dinar"  : "Dinar Iraq",
      "ok"  : "Ok",
      "cancel"  : "Cancel",

    },
    "tr":{},
    "ku":{},
  };

}